# This file was generated by CMake because it detected TRY_RUN() commands
# in crosscompiling mode. It will be overwritten by the next CMake run.
# Copy it to a safe location, set the variables to appropriate values
# and use it then to preset the CMake cache (using -C).


# BLAS_F2C_DOUBLE_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set BLAS_F2C_DOUBLE_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The BLAS_F2C_DOUBLE_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/chensi/torch-android/build/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/chensi/torch-android/build/CMakeFiles/cmTC_d1bf1-BLAS_F2C_DOUBLE_WORKS_EXITCODE
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.5/Modules/CheckCSourceRuns.cmake
#                 [2]	/home/chensi/torch-android/distro/pkg/torch/lib/TH/cmake/FindBLAS.cmake
#                 [1]	/home/chensi/torch-android/distro/pkg/torch/lib/TH/CMakeLists.txt

set( BLAS_F2C_DOUBLE_WORKS_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)


# BLAS_F2C_FLOAT_WORKS_EXITCODE
#    indicates whether the executable would have been able to run on its
#    target platform. If so, set BLAS_F2C_FLOAT_WORKS_EXITCODE to
#    the exit code (in many cases 0 for success), otherwise enter "FAILED_TO_RUN".
# The BLAS_F2C_FLOAT_WORKS_COMPILED variable holds the build result for this TRY_RUN().
# 
# Source file   : /home/chensi/torch-android/build/CMakeFiles/CMakeTmp/src.c
# Executable    : /home/chensi/torch-android/build/CMakeFiles/cmTC_fc1c6-BLAS_F2C_FLOAT_WORKS_EXITCODE
# Run arguments : 
#    Called from: [3]	/usr/share/cmake-3.5/Modules/CheckCSourceRuns.cmake
#                 [2]	/home/chensi/torch-android/distro/pkg/torch/lib/TH/cmake/FindBLAS.cmake
#                 [1]	/home/chensi/torch-android/distro/pkg/torch/lib/TH/CMakeLists.txt

set( BLAS_F2C_FLOAT_WORKS_EXITCODE 
     0
     CACHE STRING "Result from TRY_RUN" FORCE)

